name: Minecart_speedplus
main: me.esav.Minecart_speedplus.Minecart_speedplus
version: 1.2
commands:
   msp:
      description: Sets new minecart speed limit.
      usage: |
         /msp <multiplier>