name: Minecart_speedplus
main: fi.dy.esav.Minecart_speedplus.Minecart_speedplus
version: 1.2.1
commands:
   msp:
      description: Sets new minecart speed limit.
      usage: |
         /msp <multiplier>